config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'


Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'stocks#index'

  # Registration
  scope(path_names: { new: '/' }) do
    resources :users, path: 'register', only: [:new, :create]
  end

  # Login
  scope(path_names: { new: '/' }) do
    resources :sessions, path: 'login', only: [:new, :create]
  end
  post 'logout', to: 'sessions#destroy'

  # Stocks and Prices
  resources :stocks, only: [:index, :show], shallow: true do
    collection do
      resources :price_histories do
        post 'batch_create', on: :collection, defaults: { format: :json }
      end
    end

    defaults format: :json do
      member do
        resources :price_histories, only: [:index] do
          get 'sister_prices', on: :collection
        end

        resources :technical_indicators do
          post 'batch_create', on: :collection
        end
      end
    end
  end

  resources :favorites, only: [:index, :show, :create], :path => 'portfolio'
  resources :favorite
  get 'favorites/update'
  post 'portfolio/:id', to: 'favorites#destroy'

  resources :threshold, only: [:create, :destroy]
  post 'threshold/update'


  # System Administrator Endpoints
  namespace :admin do
    resources :prototype, only: [:index]
    resources :model_configs, only: [:show], defaults: { format: 'json' }
    resources :model_parameters, only: [:index, :show, :new, :create]
    post 'model_parameters/delete', to: 'model_parameters#destroy'
    post 'model_parameters/setActive', to: 'model_parameters#setActive'
    post 'model_parameters/train', to: 'model_parameters#train'
    resources :schedule, only: [:index, :edit, :update]

    defaults format: :json do
      resources :model_trainings, only: [:update] do
        post 'batch_enqueue', on: :collection
      end

      resources :price_predictions, only: [:create] do
        post 'batch_enqueue', on: :collection
      end

      resources :recommendations, only: [:create] do
        post 'batch_enqueue', on: :collection
      end
    end
  end

  mount ActionCable.server => '/websocket/:id', constraints: { id: /[\w\-\.]+/ }
  mount Sidekiq::Web => "/sidekiq"

  #Errors Custom Routes
  match '/404', via: :all, to: 'errors#not_found'
  match "/(*url)", via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'
  #get   '*path', to: sessions_url

end

app/views/navbar/_control_panel.html.erb
<div class="control-panel panel d-none">
  <div id="username"><%= current_user.full_name %></div>
  <div id="user-email"><%= current_user.email %></div>

  <%= form_with url: '/logout' do |f| %>
    <div class="text-center">
      <%= f.submit 'Log out', id: 'logout-btn', class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/navbar/_navbar.html.erb
<nav class="navbar navbar-expand navbar-light navbar-custom fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">EZML</a>

    <ul class="navbar-nav ms-auto">

      <% if logged_in? %>
      <li class="nav-item">
        <%= link_to "Portfolio", favorites_path, class: 'nav-link' %>
      </li>
      <% end %>

      <% if logged_in? && current_user.admin? %>
        <li class="nav-item">
          <%= link_to "Models", admin_model_parameters_path, class: 'nav-link' %>
        </li>
      <% end %>

      <% if logged_in? && current_user.admin? %>
        <li class="nav-item">
          <%= link_to "Schedule", admin_schedule_index_path, class: 'nav-link' %>
        </li>
      <% end %>

      <li class="nav-item">
        <% if logged_in?  %>
          <div class="account-control">
            <div id="avatar">
              <div id="user-initials"><%= current_user.initials %></div>
            </div>

            <%= render 'navbar/control_panel' %>
          </div>

        <% else %>
          <%= link_to "Login", sessions_path, class: 'nav-link' %>
        <% end  %>
      </li>
    </ul>
  </div>
</nav>
<br/>

<div class="container"> 
  <% if flash[:error].present? %>
    <br/><br/>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= flash[:error] %>
     <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <% if flash[:success].present? %>
    <br/><br/>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= flash[:success] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <% if flash[:notice].present? %>
    <br/><br/>
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      <%= flash[:notice] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

<script>
  window.setTimeout(function() {
      $(".alert").fadeTo(500, 0).slideUp(500, function(){
          $(this).remove(); 
      });
  }, 2000);
</script>