config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'


Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'stocks#index'

  # Registration
  scope(path_names: { new: '/' }) do
    resources :users, path: 'register', only: [:new, :create]
  end

  # Login
  scope(path_names: { new: '/' }) do
    resources :sessions, path: 'login', only: [:new, :create]
  end
  post 'logout', to: 'sessions#destroy'

  # Stocks and Prices
  resources :stocks, only: [:index, :show], shallow: true do
    collection do
      resources :price_histories do
        post 'batch_create', on: :collection, defaults: { format: :json }
      end
    end

    defaults format: :json do
      member do
        resources :price_histories, only: [:index] do
          get 'sister_prices', on: :collection
        end

        resources :technical_indicators do
          post 'batch_create', on: :collection
        end
      end
    end
  end

  resources :favorites, only: [:index, :show, :create], :path => 'portfolio'
  resources :favorite
  get 'favorites/update'
  post 'portfolio/:id', to: 'favorites#destroy'

  resources :threshold, only: [:create, :destroy]
  post 'threshold/update'


  # System Administrator Endpoints
  namespace :admin do
    resources :prototype, only: [:index]
    resources :model_configs, only: [:show], defaults: { format: 'json' }
    resources :model_parameters, only: [:index, :show, :new, :create]
    post 'model_parameters/delete', to: 'model_parameters#destroy'
    post 'model_parameters/setActive', to: 'model_parameters#setActive'
    post 'model_parameters/train', to: 'model_parameters#train'
    resources :schedule, only: [:index, :edit, :update]

    defaults format: :json do
      resources :model_trainings, only: [:update] do
        post 'batch_enqueue', on: :collection
      end

      resources :price_predictions, only: [:create] do
        post 'batch_enqueue', on: :collection
      end

      resources :recommendations, only: [:create] do
        post 'batch_enqueue', on: :collection
      end
    end
  end

  mount ActionCable.server => '/websocket/:id', constraints: { id: /[\w\-\.]+/ }
  mount Sidekiq::Web => "/sidekiq"

  #Errors Custom Routes
  match '/404', via: :all, to: 'errors#not_found'
  match "/(*url)", via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'
  #get   '*path', to: sessions_url

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :stock
  has_one :threshold, dependent: :destroy
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :logged_in_user
  def index
    if logged_in?
      @favorites = Favorite.where(user:current_user)
    else 
      redirect_to sessions_url
    end
    respond_to do |format|
      format.html
    end
  end

  def show
    @favorites = Favorite.find(params[:id])
    respond_to do |format|
      format.html
    end
  end  

  def update
    if logged_in?
      favorite = Favorite.where(stock: Stock.find(params[:stock]),user:current_user)
      if favorite == []
        #Create the favorite
        Favorite.create(stock: Stock.find(params[:stock]),user:current_user)
        #flash[:success] ="Stock added to favorites"
        @favorite_exists = true
      else
        favorite.destroy_all
        #flash[:notice] ="Stock removed from favorites"
        @favorite_exists = false
      end
    else 
      redirect_to sessions_url
    end
    
    respond_to do |format|
      format.html{}
      format.js{}
    end
  end

  def create
    @stocksymbol = params[:favorite][:stocksymbol].upcase
    @favorite  = Favorite.where(stock:Stock.find_by(symbol:@stocksymbol), user: current_user)
    if Stock.where(symbol:@stocksymbol).exists?
      if @favorite == [] 
      #Create favorite
        Favorite.create(stock:Stock.find_by(symbol:@stocksymbol), user: current_user)
        redirect_to favorites_path, flash: {success: "Stock added to favorites"}

        @favorite_exists = true
      else
        #Stock already existing
        redirect_to favorites_path, flash: {notice: "Stock already exists in favorites"}

      end
    else
      #No such stock symbol
      redirect_to favorites_path, flash: {error: "Stock does not exist"}

    end
  end
  
  def destroy
    @fav = Favorite.find(params[:id])
    logger.debug "Favorite should not be valid: #{@fav.valid?}"
    @fav.destroy
    @favorite_exists = false
      
    redirect_to favorites_path, flash: {success: "Stock has been removed"}
    respond_to do |format|
      format.html{}
      format.js{}
    end
  end


end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/index.html.erb
<% content_for :page_js do %>
  favorites/index
<% end %>

  <div class="container mt-5">
    <div class="row my-5">

    <div class="col-12">
        <h1>Portfolio</h1>
        <hr/>
        <br/>

        <%= form_for :favorite, :url => { :controller=> "favorites", :action => "create" } do |f| %>
          <%= f.text_field :stocksymbol, :placeholder => "Stock Symbol", :class=>"form-control", :style=>"width:250px; display:inline;" %>
          <%= f.submit "Add to Favorite", class: "btn btn-primary" %>
        <% end %>
        <br/>

        <table id="fav-list" class="table table-striped">
          <thead class="table-dark">
            <tr>
            <th scope="col">Symbol</th>
            <th scope="col">Stock Name</th>
            <th scope="col">Exchange</th>
            <th scope="col">Close</th>
            <th scope="col">Volume</th>
            <th scope="col">Change</th>
            <th scope="col">% Change</th>
            <th scope="col">Buy Threshold</th>
            <th scope="col">Sell Threshold</th>
            <th scope="col" style="width:20%">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @favorites.each do |fav| %>
              <tr class="fav_row" data-link ="<%= stock_path(fav.stock.id) %>" >
                <td id="link_to_stock" ><%= fav.stock.symbol %></td>
                <td><%= fav.stock.name %></td>
                <td><%= fav.stock.exchange %></td>
                <% fav.stock.price_histories.order(date: :desc).limit(1).each do |pxhist| %>
                    <td class="fav_close"><%= pxhist.close%></td>
                    <td><%= pxhist.volume%></td>
                    <td><%= pxhist.change.round(3)%></td>
                    <td><%= pxhist.percent_change.round(4)*100%>%</td>
                <% end %>
                <% if fav.threshold.nil? %>
                  <td> - </td>
                  <td> - </td>

                <% else %>
                  <td class="fav_buythreshold"><%= fav.threshold.buythreshold %></td>
                  <td class="fav_sellthreshold"><%= fav.threshold.sellthreshold %></td>
                
                <% end %>
                
                <td class="unclickable">

                  <!-- Button Link to Threshold Page -->
                  <%= link_to 'Threshold', fav, class: 'btn btn-success' %>

                  <!-- Button trigger modal -->
                  <%= link_to 'Un-Favorite', fav, method: :destroy, data: { confirm: 'Confirm to unfavorite the stock?', title: "Confirmation" }, class: 'btn btn-danger' %>
 
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>

app/views/favorites/show.html.erb
<div class="container">    
  <div class="row my-5">
    <div class="col-12">
      <% if @favorites.threshold.nil? %>

        <h1>Create Threshold</h1>
        <hr/>

        <h4>Add Threshold for <span class="text-primary"><%= @favorites.stock.name %></span></h4><br>
        <%= form_for :threshold, :url => { :controller=> "threshold", :action => "create", :favoriteid =>@favorites.id }, :html => {:class => "threshold_form"} do |form| %>

          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Buy Threshold</label>
            <div class="col-sm-10">
              <%= form.number_field :buythreshold, :step => 0.01, :min => 0.00, :value=>0.00, :required=>'required', :class=>'form-control', :style=>"width:250px" %>
            </div>
          </div>

          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Sell Threshold</label>
            <div class="col-sm-10">
              <%= form.number_field :sellthreshold, :step => 0.01, :min => 0.00, :value=>0.00, :required=>'required', :class=>'form-control', :style=>"width:250px" %>
              <small class="form-text">Threshold should be higher than Buy Threshold </small>
            </div>

          </div>

          <%= link_to "Back", favorites_path, class: 'btn btn-danger col-1' %>
          <%= form.submit :"Save", class: "btn btn-primary col-1" %>  
        <% end %>

      <% else %>

        <h1>Modify Threshold</h1>
        <hr/>

        <h4>Modify Threshold for <span class="text-primary"><%= @favorites.stock.name %></span></h4><br>
        <%= form_for :threshold, :url => { :controller=> "threshold", :action => "update",  :thresholdid => @favorites.threshold.id  }, :html => {:class => "threshold_form"} do |form| %>
          
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Buy Threshold</label>
            <div class="col-sm-10">
              <%= form.number_field :buythreshold, :step => 0.01, :min => 0.00, value:@favorites.threshold.buythreshold, :required=>'required', :class=>'form-control', :style=>"width:250px" %>
            </div>
          </div>

          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Sell Threshold</label>
            
            <div class="col-sm-10">
              <%= form.number_field :sellthreshold, :step => 0.01, :min => 0.00, value:@favorites.threshold.sellthreshold, :required=>'required', :class=>'form-control', :style=>"width:250px" %>
              <small class="form-text">Threshold should be higher than Buy Threshold </small>
            </div>
            
          </div>

          <%= link_to "Back", favorites_path, class: 'btn btn-danger col-1' %>
          <%= form.submit :"Update", class: "btn btn-primary col-1" %>  

        <% end %>
      <% end %>
      <% if @favorites.errors.any? %>
        <% @favorites.errors.each do |error| %>
          <%= error.full_message %>
        <% end %>
      <% end %>
    </div>

  
</div>

app/views/favorites/update.js.erb
$('#favorite_link').text("<%= favorite_text %>");