config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'


Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'stocks#index'

  # Registration
  scope(path_names: { new: '/' }) do
    resources :users, path: 'register', only: [:new, :create]
  end

  # Login
  scope(path_names: { new: '/' }) do
    resources :sessions, path: 'login', only: [:new, :create]
  end
  post 'logout', to: 'sessions#destroy'

  # Stocks and Prices
  resources :stocks, only: [:index, :show], shallow: true do
    collection do
      resources :price_histories do
        post 'batch_create', on: :collection, defaults: { format: :json }
      end
    end

    defaults format: :json do
      member do
        resources :price_histories, only: [:index] do
          get 'sister_prices', on: :collection
        end

        resources :technical_indicators do
          post 'batch_create', on: :collection
        end
      end
    end
  end

  resources :favorites, only: [:index, :show, :create], :path => 'portfolio'
  resources :favorite
  get 'favorites/update'
  post 'portfolio/:id', to: 'favorites#destroy'

  resources :threshold, only: [:create, :destroy]
  post 'threshold/update'


  # System Administrator Endpoints
  namespace :admin do
    resources :prototype, only: [:index]
    resources :model_configs, only: [:show], defaults: { format: 'json' }
    resources :model_parameters, only: [:index, :show, :new, :create]
    post 'model_parameters/delete', to: 'model_parameters#destroy'
    post 'model_parameters/setActive', to: 'model_parameters#setActive'
    post 'model_parameters/train', to: 'model_parameters#train'
    resources :schedule, only: [:index, :edit, :update]

    defaults format: :json do
      resources :model_trainings, only: [:update] do
        post 'batch_enqueue', on: :collection
      end

      resources :price_predictions, only: [:create] do
        post 'batch_enqueue', on: :collection
      end

      resources :recommendations, only: [:create] do
        post 'batch_enqueue', on: :collection
      end
    end
  end

  mount ActionCable.server => '/websocket/:id', constraints: { id: /[\w\-\.]+/ }
  mount Sidekiq::Web => "/sidekiq"

  #Errors Custom Routes
  match '/404', via: :all, to: 'errors#not_found'
  match "/(*url)", via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'
  #get   '*path', to: sessions_url

end

app/controllers/admin/schedule_controller.rb
module Admin
    class ScheduleController < ApplicationController
        before_action :redirect_if_not_admin
        def index
            @models = ModelConfig.all
            @schedule = TrainingSchedule.all
        end


        def edit
            @schedule = TrainingSchedule.find(params[:id])
            respond_to do |format|
                format.html{}
                format.js{}
            end
        end

        def update
            @schedule = TrainingSchedule.find(params[:id])
            if @schedule.update(schedule_params)
                flash[:success] = "Schedule is successfully updated"
                redirect_to admin_schedule_index_path
            else
                flash[:error] = "Schedule update has failed"
                render :edit
            end

        end

        private

        def schedule_params
            params.require(:training_schedule).permit(:start_date,:frequency)
        end
                
    end 
end

app/helpers/admin/schedule_helper.rb
module Admin::ScheduleHelper
end

app/views/admin/schedule/edit.html.erb
<div class="container" style="margin-bottom: 20px">
  <div class="row my-5">
    <div class="col-12">
      <h1>Edit Schedule</h1>
      <hr/>

      <h4>Edit Schedule for <span class="text-primary"><%= @schedule.model_config.name %></span></h4><br>
      <br/>

      <%= form_with model: @schedule, action: :update, url: admin_schedule_path(@schedule), local: true do |f| %>

        <div class="form-group row">
          <label class="col-sm-2 col-form-label"><%= f.label :start_date, class: "form-label" %></label>
          <div class="col-sm-10">
            <%= f.date_field :start_date, min: @schedule.start_date, max: Date.today+61, required: true, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-sm-2 col-form-label"><%= f.label :Frequency, class: "form-label" %></label>
          <div class="col-sm-10">
            <%=
            f.select(:frequency,
                    [['7',7],['14',14],['21',21]],
                    { },
                    { required: true, class: "form-control"})
            %>
          </div>
        </div>

        <%= link_to "Back", admin_schedule_index_path, class: 'btn btn-danger col-1' %>
        <%= f.submit :"Save", class: "btn btn-primary col-1" %>

        <% if local_assigns.has_key? :status_msg %>
          <p><%= status_msg %></p>
        <% end %>
      <% end %>
    </div>
  </div>

</div>

app/views/admin/schedule/index.html.erb
<div class="container mt-5">
  <div class="row my-5">
    <div class="col-12">
      <h1>Schedule</h1>
      <hr/>
      <br/>

      <table class="table">
        <thead class="table-dark">
          <tr>
            <th scope="col">Model Parameters Config Name</th>
            <th scope="col">Schedule Date</th>
            <th scope="col">Frequency (Days)</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @schedule.order({ created_at: :desc }).each do |schedule| %>
            <tr>
              <td><%= schedule.model_config.name %></td>
              <td><%= schedule.start_date %></td>
              <td><%= schedule.frequency %></td>
              <td>
                <%= link_to "Edit", edit_admin_schedule_path(id:schedule), method: :get, class: 'btn btn-primary' %>
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>
    </div>
  </div>
 
</div>

app/views/admin/schedule/new.html.erb
<div class="container" style="margin-bottom: 20px">
  <h1>Edit Schedule</h1>
  <hr/>

  <% if flash[:error].present? %>
    <div class="alert alert-danger"><%= flash[:error] %></div>
  <% end %>
  <% if flash[:success].present? %>
    <div class="alert alert-success"><%= flash[:success] %></div>
  <% end %>

  <%= form_with model: @ml_params, method: :post, url: admin_model_parameters_path, local: true do |f| %>


    <div class = "mb-3">
    <%= f.label :start_date, class: "form-label" %>
    <%= f.date_field :start_date, required: true, class: "form-control" %>
    </div>


    <div class="mb-3" id="gamma">
    <%= f.label :Frequency, class: "form-label" %><br>
    <%=
    f.select(:frequency,
            [['7',7],['14',14],['21',21]],
            { },
            {class: "form-control"})
    %>
    </div>



    <%= link_to "Back", "/admin/schedule", class: 'btn btn-danger col-1' %>
    <%= f.submit :"Submit", class: "btn btn-primary col-1" %>

    <% if local_assigns.has_key? :status_msg %>
      <p><%= status_msg %></p>
    <% end %>
  <% end %>
</div>