config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'


Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'stocks#index'

  # Registration
  scope(path_names: { new: '/' }) do
    resources :users, path: 'register', only: [:new, :create]
  end

  # Login
  scope(path_names: { new: '/' }) do
    resources :sessions, path: 'login', only: [:new, :create]
  end
  post 'logout', to: 'sessions#destroy'

  # Stocks and Prices
  resources :stocks, only: [:index, :show], shallow: true do
    collection do
      resources :price_histories do
        post 'batch_create', on: :collection, defaults: { format: :json }
      end
    end

    defaults format: :json do
      member do
        resources :price_histories, only: [:index] do
          get 'sister_prices', on: :collection
        end

        resources :technical_indicators do
          post 'batch_create', on: :collection
        end
      end
    end
  end

  resources :favorites, only: [:index, :show, :create], :path => 'portfolio'
  resources :favorite
  get 'favorites/update'
  post 'portfolio/:id', to: 'favorites#destroy'

  resources :threshold, only: [:create, :destroy]
  post 'threshold/update'


  # System Administrator Endpoints
  namespace :admin do
    resources :prototype, only: [:index]
    resources :model_configs, only: [:show], defaults: { format: 'json' }
    resources :model_parameters, only: [:index, :show, :new, :create]
    post 'model_parameters/delete', to: 'model_parameters#destroy'
    post 'model_parameters/setActive', to: 'model_parameters#setActive'
    post 'model_parameters/train', to: 'model_parameters#train'
    resources :schedule, only: [:index, :edit, :update]

    defaults format: :json do
      resources :model_trainings, only: [:update] do
        post 'batch_enqueue', on: :collection
      end

      resources :price_predictions, only: [:create] do
        post 'batch_enqueue', on: :collection
      end

      resources :recommendations, only: [:create] do
        post 'batch_enqueue', on: :collection
      end
    end
  end

  mount ActionCable.server => '/websocket/:id', constraints: { id: /[\w\-\.]+/ }
  mount Sidekiq::Web => "/sidekiq"

  #Errors Custom Routes
  match '/404', via: :all, to: 'errors#not_found'
  match "/(*url)", via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'
  #get   '*path', to: sessions_url

end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :price_histories,      dependent: :destroy
  has_many :technical_indicators, dependent: :destroy
  has_many :price_predictions,    dependent: :destroy
  has_many :recommendations,      dependent: :destroy
  has_many :model_trainings,      dependent: :destroy
  has_many :model_configs,        through: :model_trainings

  enum industry: { technology: 'technology', energy: 'energy', healthcare: 'healthcare' }

  auto_strip_attributes :symbol, :name, :exchange
  before_validation :upcase_symbol

  validates :symbol,    presence: true, uniqueness: true
  validates :name,      presence: true
  validates :exchange,  presence: true
  validates :industry,  presence: true


  private

    def upcase_symbol
      self.symbol.upcase! if symbol.present?
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @stocks = Stock.all
    latest_changes = @stocks.select {|s| s.price_histories.count > 0}.map {|s|
      change = s.price_histories.last.percent_change
      { symbol: s.symbol, change: change.to_f }
    }.sort_by {|s| s[:change]}.reverse

    best_changes = latest_changes.select{ |item| item[:change] > 0 }
    worst_changes = latest_changes.select{ |item| item[:change] <= 0 }

    max_performer = 10
    count_best = best_changes.length() >= max_performer ? max_performer : best_changes.length()
    count_worst = worst_changes.length() >= max_performer ? max_performer : worst_changes.length()

    @ranked = {
      "Best": best_changes[0..count_best-1],
      "Worst": worst_changes[-count_worst..-1].reverse
    }

    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    @stock = Stock.find(params[:id])

    @recent_predictions = @stock.price_predictions.order(reference_date: :desc, created_at: :desc)
                                .limit(5).map {|s| s.to_chart_json }

    @recommendation_action = @stock.recommendations.order(prediction_date: :desc, created_at: :desc)
                                   .limit(1)

    @favorite_exists = Favorite.where(stock: @stock, user:current_user) == [] ? false : true
    respond_to do |format|
      format.html
    end
  end
end

app/helpers/stock_helper.rb
module StockHelper
end

app/views/stocks/index.html.erb
<% content_for :page_js do %>
  stocks/index
<% end %>

<% content_for :assets do %>
  <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
<% end %>


<!-- SECTION 1 -->
<div class="container-fluid px-0">
  <div class="row mx-0">
    <div class="img-wrapper col-12 px-0">
      <img src="/images/stockmarket.jpeg" class="img-responsive img-fluid w-100" />
      <div class="img-overlay">
        <h1>WELCOME TO EZML</h1>
        <p>YOUR PERSONAL AI STOCK PREDICTOR</p>
        <a href="#stocks-list" class="btn shrink-border btn-explore">Explore</a>
      </div>
    </div>
  </div>
</div>

<!-- SECTION 2 -->
<div class="container my-5">
  <%# <h1>SYNOPSIS PLACEHOLDER</h1> %>
</div>

<!-- SECTION 3 -->
<div class="container">
  <div class="row my-5">
    <% @ranked.each do |rank, data| %>
      <div class="col-6">
        <h1><%= "#{rank} performers".upcase %></h1>

        <table id=<%= "#{rank.to_s.rpartition(' ').last}-stocks" %> class="table table-striped">
          <thead class="<%= rank.to_s.rpartition(' ').last.upcase == "BEST" ? "table-success" : "table-danger"%>">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Stock</th>
              <th scope="col">Percent Change</th>
              <th scope="col">Movement</th>
            </tr>
          </thead>
          <tbody>
          <% data.each_with_index do |d, idx| %>
            <tr>
              <td><%= idx + 1 %></td>
              <td><%= d[:symbol] %></td>
              <td><%= d[:change] %></td>
              <td>
                <% if d[:change] > 0 %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-up-fill" viewBox="0 0 16 16">
                    <path d="m7.247 4.86-4.796 5.481c-.566.647-.106 1.659.753 1.659h9.592a1 1 0 0 0 .753-1.659l-4.796-5.48a1 1 0 0 0-1.506 0z"/>
                  </svg>
                <% elsif d[:change] < 0 %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-down-fill" viewBox="0 0 16 16">
                    <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
                  </svg>
                <% else %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash" viewBox="0 0 16 16">
                    <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z"/>
                  </svg>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>


<!-- SECTION 4 -->
<div class="container">
  <div class="row my-5">
    <div class="col-12">
      <h1>STOCKS LIST</h1>

      <table id="stocks-list" class="table table-striped table-hover">
        <thead class="table-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Symbol</th>
            <th scope="col">Name</th>
            <th scope="col">Exchange</th>
            <th scope="col">Industry</th>
          </tr>
        </thead>
      </table>
    </div>
  </div>
</div>

app/views/stocks/show.html.erb
<% content_for :page_js do %>
  stocks/show
<% end %>

<% content_for :assets do %>
  <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
<% end %>


<div class="container">
  <!-- PRICE CHART -->
  <div class="row my-5">
    <div class="col-12">
      <br/>
      <h1 id="stockname" style="display: inline"><%= @stock.symbol %> </h1>

      <% if @recommendation_action.count > 0 %>
        <% if @recommendation_action.first.verdict.upcase == "SELL" %>
          <span class="badge bg-danger text-wrap" style="font-size: 20px;">
            <%= @recommendation_action.first.verdict.upcase %>
          </span>
        <% elsif @recommendation_action.first.verdict.upcase == "BUY" %>
          <span class="badge bg-success text-wrap" style="font-size: 20px;">
            <%= @recommendation_action.first.verdict.upcase %>
          </span>
        <% else %>
          <span class="badge bg-warning text-wrap" style="font-size: 20px;">
            <%= @recommendation_action.first.verdict.upcase %>
          </span>
        <% end %>

        <span class="fs-3 text-secondary">
          on <%= @recommendation_action.first.prediction_date %>
        </span>
      <% end %>

      <% if logged_in? %>
        <%= link_to favorite_text, favorites_update_path(stock:@stock), class:'btn btn-primary', style:'margin-top:30px; float:right;', id:'favorite_link', remote: true %>
      <% else %>
        <%= link_to "Log in to add", sessions_path, class:'btn btn-primary', style:'margin-top:30px; float:right;' %>
      <% end %>

      <h3 id="stockfullname"><%= @stock.name %></h3>

    </div>

    <div class="col-12">
      <span id="stockexchange" style="visibility: hidden"><%=@stock.exchange%></span>
      <div id="tradingview_Chart"></div>
    </div>
  </div>


   <!-- PRICE RELATED DATA -->
  <div class="row my-5">
    <div class="col-12">
      <h1>LAST 5 PRICE DATA</h1>

      <table id="pricehistory-list" class="table table-striped ">
        <thead class="table-dark">
          <tr>
            <th>Date</th>
            <th>Open</th>
            <th>High</th>
            <th>Low</th>
            <th>Close</th>
            <th>Volume</th>
            <th>Change</th>
            <th>% Change</th>
          </tr>
        </thead>
        <tbody>
          <% @stock.price_histories.order(date: :desc).limit(5).each do |pxhist| %>
            <tr>
              <td><%= pxhist.date%></td>
              <td><%= pxhist.open%></td>
              <td><%= pxhist.high%></td>
              <td><%= pxhist.low%></td>
              <td><%= pxhist.close%></td>
              <td><%= pxhist.volume%></td>
              <td><%= pxhist.change.round(3)%></td>
              <td><%= pxhist.percent_change.round(4)*100%>%</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>


  <!-- PREDICTION FROM ML -->
  <h1>STOCKS PREDICTION</h1>
  <div class="row my-5">
    <div class="col-5">
      <%= content_tag :div,
        class: "price_prediction",
        data: { pxpredict: @recent_predictions.first } do
      %>
        <canvas id="line-chart" width="350" height="200"></canvas>
      <% end %>

    </div>

    <div class="col-7">
      <table id="pricepredict-list" class="table table-striped">

        <thead>
          <tr>
            <th class="bg-secondary">Ref Date</th>
            <th class="bg-primary">ST Date</th>
            <th class="bg-primary">ST Prc</th>
            <th class="bg-warning">MT Date</th>
            <th class="bg-warning">MT Prc</th>
            <th class="bg-success">LT Date</th>
            <th class="bg-success">LT Prc</th>
          </tr>
        </thead>
        <tbody>
          <% @recent_predictions.each do |prices| %>
              <tr>
                <td class="table-secondary"><%= prices[:reference_date] %></td>
                <td class="table-primary"><%= prices[:st_date] %></td>
                <td class="table-primary"><%= prices[:st_exp_price] %></td>
                <td class="table-warning"><%= prices[:mt_date] %></td>
                <td class="table-warning"><%= prices[:mt_exp_price] %></td>
                <td class="table-success"><%= prices[:lt_date] %></td>
                <td class="table-success"><%= prices[:lt_exp_price] %></td>
              </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>

</div>